<?php
// $Id$

/**
 * Implementation of hook_block()
 */
function bangpoundthemer_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $info['theme_tools'] = array(
        'info' => t('Theme tools'),
        'cache' => BLOCK_CACHE_GLOBAL,
      );
      $info['mockups'] = array(
        'info' => t('Mockups'),
        'cache' => BLOCK_CACHE_GLOBAL,
      );
      return $info;

    case 'view':
      $block = array();
      switch ($delta) {
        case 'theme_tools':
          $items[] = "<a href=\"javascript:function%20fnStartDesign(sUrl)%20%7Bvar%20nScript%20=%20document.createElement('script');nScript.setAttribute('language','JavaScript');nScript.setAttribute('src',sUrl);document.body.appendChild(nScript);%7DfnStartDesign('http://www.sprymedia.co.uk/design/design/media/js/design-loader.js');\">". t('Design') ."</a>";
          $items[] = "<a href=\"javascript:function%20loadScript(scriptURL)%20%7B%20var%20scriptElem%20=%20document.createElement('SCRIPT');%20scriptElem.setAttribute('language',%20'JavaScript');%20scriptElem.setAttribute('src',%20scriptURL);%20document.body.appendChild(scriptElem);%7DloadScript('http://westciv.com/xray/thexray.js');\">". t('XRAY') ."</a>";
          $items[] = "<a href=\"javascript:$('body').toggleClass('bangpound-debug');\">Debug theme</a>";
          $items[] = "<a href=\"http://validator.w3.org/check?uri=referer\"><img src=\"http://www.w3.org/Icons/valid-xhtml10\" alt=\"Valid XHTML 1.0 Strict\" height=\"31\" width=\"88\" /></a>";
          $items[] = "<a href=\"javascript:var firebug=document.createElement('script');firebug.setAttribute('src','http://getfirebug.com/releases/lite/1.2/firebug-lite-compressed.js');document.body.appendChild(firebug);(function(){if(window.firebug.version){firebug.init();}else{setTimeout(arguments.callee);}})();void(firebug);\">". t('Firebug Lite') ."</a>";
          $block['subject'] = t('Theme tools');
          $block['content'] = theme('item_list', $items);
          return $block;
        case 'mockups':
          global $theme;
          $path = drupal_get_path('theme', $theme);
          jquery_ui_add(array('ui.draggable', 'ui.slider'));
          drupal_add_js(drupal_get_path('module', 'bangpoundthemer') .'/mockups.js');
          if (user_access('access content')) {
            $items = array();
            $results = array();
            $handler = opendir($path .'/images/mocks');

            // keep going until all files in directory have been read
            while ($file = readdir($handler)) {
              if ($file != '.' && $file != '..') {
                $results[] = $file;
              }
            }
            closedir($handler);
            foreach ($results as $mockup) {
              $items[] = l($mockup, $path .'/images/mocks/'. $mockup);
            }
            $block['subject'] = t('Mockups');
            $block['content'] = theme('item_list', $items);
            return $block;
          }
        default:
          break;
      }
  }
}
